vuejs/rollup-plugin-vue

README.md, dist/rollup-plugin-vue.common.js, dist/rollup-plugin-vue.js, src/index.js, src/vueTransform.js
=> Update css callback as in proposal 

README.md, package.json, src/index.js, src/options.js, src/vueTransform.js, test/expects/compileTemplate.js, test/fixtures/compileTemplate.vue, test/test.js
Add support to compile Vue 2 templates.
The code can be reviewed already.
I'll add tests and some doc tomorrow.
I didn't rebase the commits because of the squash feature, but tell me if you want me to do it
=> Fix #19 Compile Vue 2 templates

package.json, src/index.js, src/vueTransform.js, test/expects/compileTemplate.js, test/fixtures/compileTemplate.vue, yarn.lock
Using it to transpile the render code generated allows to remove `with`
statements, making the generated code strict mode compatible
=> Add vue-template-es2015-compiler

src/vueTransform.js
Do not try to compile the template of a vue file if it doesn't exist.
This may hapen in Vue files using pure render functions
=> 🐛 Compile vue files without a template

src/vueTransform.js, test/expects/slot.js, test/expects/table-n-slot.js, test/expects/table.js, test/fixtures/table-n-slot.vue, test/test.js
Fixes #55 
- Suppress warnings when compiling template.
=> Suppress warnings when compiling template

docs/config.js, docs/index.html
=> Upgrade to docute 3

config/build.js, docs/en/2.3/README.md, src/options.js, src/style/index.js, src/style/stylus.js, test/expects/no-css-extract.js, test/expects/stylus.css, test/expects/stylus.js, test/fixtures/no-css-extract.vue, test/fixtures/stylus.vue, test/test.js
Fixes #78, support for Stylus.
- allow the use of <style lang="stylus"> in single-file components
/ping @znck
=> Integrate Stylus.

src/script/coffee.js, src/style/less.js, src/style/scss.js, src/style/stylus.js, src/template/pug.js
Fixes #83 .
- Each optional dependency now is required when the related function is actually used, not always at start.
/ping @znck
Didn't add tests for this because a test would be running the compiled version in node with and without the required packages, and I'm not sure if you want that...
=> Make optional dependencies really optional

docs/en/2.3/README.md
- Update the v2.3 documentation and address the name of `styleToImports`, which was erroneously called `styleToImport`. This is to prevent many headaches by future developers!
/ping @znck
=> Use the right name for `styleToImports` in documentation

src/options.js, test/expects/compileTemplateLocalComponent.js, test/fixtures/compileTemplateLocalComponent.vue, test/test.js
Currently the compiled result of a template yields a lowercase version
while it should keep the original case.
Helps #81 .
/ping @znck
=> Preserve case in templates

src/template/pug.js, test/expects/pug.js, test/fixtures/pug.vue
Fixes #86 .
- Trim templates code before pug-template compiling, so that the compiler works correctly however many indent before the first letter of the very first line.
/ping @znck
=> Trim templates before pug compiling (#86)

src/template/pug.js, src/vueTransform.js, test/expects/pug.js, test/fixtures/pug.vue
Fixes #86. This should give template preprocessor more consistent code. vue-template-compiler also deindent before preprocessing.
/ping @znck
=> Fix #86, deIndent template code before preprocessing

src/vueTransform.js, test/expects/scoped-css-with-no-auto-style.css, test/expects/scoped-css-with-no-auto-style.js, test/fixtures/scoped-css-with-no-auto-style.vue, test/test.js
Fixes #91 
- Add failing tests for scoped styles and css modules when auto styles is turned off
- Fix issue #91
=> Fix #91, Process scoped styles and css modules when auto styles is turned off

src/options.js, src/style/less.js, src/style/scss.js, src/style/stylus.js
Fixes #93 
- Prepends snippet set in `data` option of `scss`, `less` or `stylus` to each component.
=> Allow data option to prepend style to scss, less, stylus blocks

docs/config.js, docs/en/2.2/README.md, docs/en/2.3/README.md, docs/en/2.3/examples.md
since this doc is indexed by `version` variable https://github.com/algolia/docsearch-configs/blob/master/configs/rollup-plugin-vue.json#L7
/ping @znck
=> [docs] fix search keyword

src/style/css.js, test/expects/scoped-css-with-deep-tag.css, test/expects/scoped-css-with-deep-tag.js, test/fixtures/scoped-css-with-deep-tag.vue, test/test.js
Follow vue-loader to support `/deep/` and `>>>`
also fixes #108 .
/ping @znck
=> support /deep/ and >>>

src/index.js
- use regex to extract component name when using style to import feature.
=> fix: use regex to extract component and style index

package.json, src/options.js, src/style/css.js, src/style/postcss.js, test/expects/postcss.css, test/expects/postcss.js, test/expects/scoped-css-with-deep-tag.css, test/fixtures/postcss.vue, test/test.js, yarn.lock
Fixes #102 #118 #122 .
- support postcss
Previously, "module" and "scoped" cannot be set at the same time, only "module" has effect, this PR fix this.
I will try to solve css sourcemap issue, haven't got a clue yet.
/ping @znck
=> support postcss

config/build.js, docs/en/2.3/README.md, src/style/postcss.js, test/test.js
make `postcss`'s option consistent with `vue-loader`;
fix a build warning;
Fixes #125 .
- add `postcss` document
- make `postcss` option be consistent with `vue-loader`
- fix a build warning: `postcss-load-config'` can't be resolved
English is not my first language, so please help me to make it more readable.
/ping @znck
=> add `postcss` document;

src/style/index.js
- Add ability to use `lang="postcss"` on `<style>` tags, this is needed for proper editor highlighting.
/ping @znck
=> Add ability for lang="postcss" on style tags

src/style/less/index.js, test/expects/empty-less.css, test/expects/empty-less.js, test/fixtures/empty-less.vue, test/test.js
Fixes #132.
- Add null check for results of less.render
/ping @znck
=> Allow less style which is empty or comments only

example/rollup.config.js
=> fix: edit example conf.js

package.json, src/style/css.js, src/vueTransform.js, yarn.lock
- Upgrade PostCSS to `6.0.*`
- Fix issue where plugins could execute multiple times due to direct modification of plugins array
/ping @znck
=> Upgrade PostCSS to 6.0.*

package.json, src/index.js, test/baseline.spec.js, test/setup/index.js, yarn.lock
Always inject scopeId to component options when using scoped CSS
=> fix: When using extract CSS add scopeId

src/index.ts, src/utils.ts
=> fix: Use file basename in vue block imports

package.json, src/utils.ts, test/fixtures/with-script-typescript.vue, test/setup/index.ts, test/setup/plugins.ts, yarn.lock
=> fix: Handle Vue.extend constructor export from .vue file

package.json
Just expose `rollup-plugin-vue`'s TypeScript declarations for TypeScript developers.
/ping @znck
=> 👐 Expose TypeScript declarations

src/index.ts, test/forward-style-compiler-errors.spec.ts
Fixes #226.
- forward the errors returned from `compileStyleAsync` to alert user that something has went wrong.
/ping @znck
=> fix: Throw style compilation errors

src/index.ts
scss processor modifies descriptor.styles[x].map.mappings and
`parse` function from `component-compiler-utils` caches the parsing
result. These two combined would cause a bug when rolling-up
multiple-output configuration since the descriptor is modified and
cached in the first turn and causing successive turns to fail.
Fixes #241 #239 .
- copies SFCDescriptor before further manipulating it as https://github.com/vuejs/component-compiler-utils/pull/35#issuecomment-433740673 says
/ping @znck
=> fix: Copies SFCDescriptor before further passing it to processors

test/setup/plugins.ts
Fixes #253 
- use `JSON.stringify()` to JS-encode import paths
- this fixes tests on Windows
/ping @znck
=> fix: Properly encode testfixture imports

src/index.ts
(No issue open for this)
- Using `template.isProduction` if explicitly set to determine production before environment variables
/ping @znck
=> Fixing template.isProduction option

package.json, yarn.lock
Fixes N/A. I haven't logged it as an issue. Let me know if it's required!
- Upgrade `rollup-pluginutils`
Running `yarn audit` in a project using latest version of `rollup-plugin-vue` (at the time of writing `4.7.2`) has 2 low level security issues. Both of which are a result of outdated `rollup-pluginutils`. Latest version of `rollup-pluginutils` is a minor upgrade and uses latest version of `braces` which doesn't have the "Regular Expression Denial of Service" issue. As for the "Cryptographically Weak PRNG" issue - `braces` package no longer depends on `expand-rage`.
I also ran the tests after upgrade, just for safe measure, and all tests passed.
```
yarn audit v1.13.0
┌───────────────┬──────────────────────────────────────────────────────────────┐ …
```
=> chore: Upgrade rollup-pluginutils

package.json, yarn.lock
Fixes #263 (I think). Testing locally fixed the SSR problems I was seeing related to `document is undefined` when looking for head that was replaced [here](https://github.com/znck/vue-runtime-helpers/commit/02d9dfaf54388128a7eac8013f0af6526f6e8586)
- Upgrade `vue-runtime-helpers`
/ping @znck
=> chore: Upgrade vue-runtime-helpers

package.json, src/index.ts, src/utils.ts, test/options/__snapshots__/custom-blocks.spec.ts.snap, test/options/custom-blocks.spec.ts, yarn.lock
Based on work by @kazupon  in #309
=> fix: call transformer from whitelisted custom blocks

tsconfig.json
issue https://github.com/ezolenko/rollup-plugin-typescript2/issues/105
Fixes #.
After transpile async await syntax, it is now working fine with `rollup-plugin-typescript2`
/ping @znck
=> fix(tsconfig.json): transpile async await in order to be compatible to rollup-plugin-typescript2

README.md
=> fix some wording

docs/faqs.md
- adds syntax highlighting
/ping @znck
=> docs(faq): add syntax highlighting

cookbook/ssr/package.json, cookbook/ssr/src/MyComponent.vue, src/index.ts
Fixes #321
- Generate compiler instance per component so component `scopeId` can be passed as a variable to generate correctly optimised SSR code.
I tried to add tests for that but it seems that currently tests enviroment supports only `iife` build.
/ping @znck
=> fix: generate compiler per component to pass information about scopeId

.github/workflows/ci.yaml, jest.config.js, src/index.spec.ts, src/index.ts
=> feat: process custom blocks

src/index.ts
=> feat: distinguish options for different CSS preprocessing languages

README.md
Fixes minor doc detail.
- Seems [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) has been moved to [@rollup/plugin-commonjs](https://github.com/rollup/plugins/tree/master/packages/commonjs)
/ping @znck
=> docs: reference new rollup commonjs plugin

README.md
Add the NPM badge to help an user immediately get to the corresponding library page on `npm.com` from the `github.com` page.
- Add the NPM badge to README.md
/ping @znck
=> docs: add the npm badge

src/index.ts
- The default `templateImport` should also be aware of the `isServer` flag
Similar to https://github.com/vuejs/vue-loader/blob/a56585e707a69de41a1fd083f5f2018e271d1e1c/src/index.ts#L155
/ping @znck
=> fix: default render function name for ssr
